//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBelleza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito_detalles
    {
        public int id_detalle { get; set; }
        public int id_carrito { get; set; }
        public Nullable<int> id_producto { get; set; }
        public int cantidad { get; set; }
        public Nullable<decimal> precio_unitario { get; set; }
    
        public virtual carrito carrito { get; set; }
        public virtual producto producto { get; set; }
    }
}
