//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBelleza.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tienda_bellezaEntities1 : DbContext
    {
        public tienda_bellezaEntities1()
            : base("name=tienda_bellezaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<carrito> carritoes { get; set; }
        public virtual DbSet<carrito_detalles> carrito_detalles { get; set; }
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<consultora> consultoras { get; set; }
        public virtual DbSet<detalle_ordenes> detalle_ordenes { get; set; }
        public virtual DbSet<direccione> direcciones { get; set; }
        public virtual DbSet<envio> envios { get; set; }
        public virtual DbSet<marca> marcas { get; set; }
        public virtual DbSet<ordene> ordenes { get; set; }
        public virtual DbSet<producto> productos { get; set; }
        public virtual DbSet<productos_promocion> productos_promocion { get; set; }
        public virtual DbSet<promocione> promociones { get; set; }
        public virtual DbSet<subcategoria> subcategorias { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
