//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBelleza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consultora
    {
        public int id_consultora { get; set; }
        public int id_usuario { get; set; }
        public string zona { get; set; }
        public string codigo_referido { get; set; }
        public string estado { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
