//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBelleza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public direccione()
        {
            this.ordenes = new HashSet<ordene>();
        }
    
        public int id_direccion { get; set; }
        public int id_usuario { get; set; }
        public string direccion { get; set; }
        public string ciudad { get; set; }
        public string departamento { get; set; }
        public string codigo_postal { get; set; }
        public string pais { get; set; }
    
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordene> ordenes { get; set; }
    }
}
