//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBelleza.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class envio
    {
        public int id_envio { get; set; }
        public int id_orden { get; set; }
        public string empresa_envio { get; set; }
        public string codigo_seguimiento { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public Nullable<bool> confirmado_por_cliente { get; set; }
        public Nullable<System.DateTime> fecha_confirmacion_cliente { get; set; }
    
        public virtual ordene ordene { get; set; }
    }
}
