//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaBelleza.Models
{
    using System;
    using System.Collections.Generic;

    public partial class producto
    {
        public producto()
        {
            this.carrito_detalles = new HashSet<carrito_detalles>();
            this.detalle_ordenes = new HashSet<detalle_ordenes>();
            this.productos_promocion = new HashSet<productos_promocion>();
        }

        public int id_producto { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> stock { get; set; }
        public string imagen { get; set; }
        public Nullable<int> id_subcategoria { get; set; }
        public Nullable<int> id_marca { get; set; }
        public string tipo_producto { get; set; }
        public string genero { get; set; }

        public virtual ICollection<carrito_detalles> carrito_detalles { get; set; }
        public virtual ICollection<detalle_ordenes> detalle_ordenes { get; set; }
        public virtual ICollection<productos_promocion> productos_promocion { get; set; }
        public virtual marca marca { get; set; }
        public virtual subcategoria subcategoria { get; set; }
    }
}
